# Generated by Django 2.1.2 on 2019-04-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('image', models.URLField()),
                ('sourceAPI', models.CharField(max_length=100)),
                ('recipeLink', models.URLField()),
                ('readyInMinutes', models.IntegerField()),
                ('instruction', models.CharField(max_length=10000)),
                ('ingredients', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
