# Generated by Django 2.1.2 on 2019-04-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodPrepIt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheRecipeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('image', models.URLField()),
                ('sourceAPI', models.CharField(max_length=100)),
                ('recipeLink', models.URLField()),
                ('readyInMinutes', models.IntegerField()),
                ('instruction', models.CharField(max_length=10000)),
                ('ingredients', models.CharField(max_length=1000)),
                ('diet', models.CharField(max_length=300)),
                ('excludeIngredients', models.CharField(max_length=300)),
                ('budget', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
