# Generated by Django 2.1.2 on 2019-04-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodPrepIt', '0002_cacherecipedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacherecipedetail',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='cacherecipedetail',
            name='excludeIngredients',
        ),
        migrations.AlterUniqueTogether(
            name='cacherecipedetail',
            unique_together={('title', 'sourceAPI')},
        ),
    ]
