# Generated by Django 2.1.2 on 2019-04-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodPrepIt', '0003_auto_20190403_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('image', models.URLField()),
                ('sourceAPI', models.CharField(max_length=100)),
                ('recipeLink', models.URLField()),
                ('readyInMinutes', models.IntegerField()),
                ('instruction', models.CharField(max_length=10000)),
                ('ingredients', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
